name: ✅ Test installer
on:
  push:
    branches: [main]
    paths:
      - "./build.sh"
  pull_request:
    branches: [main]
    paths:
      - "./build.sh"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: 🏗 Run installer
        run: |
          sudo apt-get update && sudo apt-get install zsh
          ci=1 ./build.sh
      - run: |
          module_path+=( "/home/runner/.zi/zmodules/zpmod/Src" )
          zmodload zi/zpmod
          zpmod source-study -l
        shell: zsh {0}
