---
name: ✅ Build (MacOS)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3.2.0
      - name: ☑️ ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./Scripts/install.sh"

  build:
    runs-on: macos-latest
    timeout-minutes: 30
    needs: [shellcheck]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3.2.0
      - uses: rlespinasse/github-slug-action@v4
      - name: 🍎 Prepare
        run: |
          brew install zsh
      - name: 🍎 Build
        run: sh ./Scripts/install.sh && ls -a $HOME/.zi/zmodules/zpmod/Src/zi
        #run: |
        #  module_path+=( "$HOME/.zi/zmodules/zpmod/Src" )
        #  zmodload zi/zpmod
        #  zpmod source-study -l
